accounts/urls.py
from django.urls import path
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [
    path('login/', LoginView.as_view(
        redirect_authenticated_user=True,
        template_name='accounts/login.html'
    ), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

adminSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('detail/<int:article_id>', views.detail, name='detail'),
    path('edit/<int:article_id>', views.edit, name='edit'),
    path('delete/<int:article_id>', views.delete, name='delete'),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()

    def __str__(self):
        return f'{self.title}, {self.content}'

blog/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'

accounts/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Article
from .forms import ArticleForm
from django.contrib.auth.decorators import login_required # --- 追記


@login_required
def index(request):
    articles = Article.objects.all()
    params = {
        'articles': articles,
    }
    return render(request, 'blog/index.html', params)


@login_required
def create(request):
    if (request.method == 'POST'):
        obj = Article()
        article = ArticleForm(request.POST, instance=obj)
        article.save()
        return redirect('index')
    else:
        params = {
            'form': ArticleForm(),
        }
        return render(request, 'blog/create.html', params)


def detail(request, article_id):
    article = Article.objects.get(id=article_id)
    params = {
        'article': article,
    }
    return render(request, 'blog/detail.html', params)


def edit(request, article_id):
    article = Article.objects.get(id=article_id)
    if (request.method == 'POST'):
        article.title = request.POST['title']
        article.content = request.POST['content']
        article.save()
        return redirect('detail', article_id)
    else:
        form = ArticleForm(initial={
            'title': article.title,
            'content': article.content,
            })
        params = {
            'article': article,
            'form': form,
        }
        return render(request, 'blog/edit.html', params)


def delete(request, article_id):
    article = Article.objects.get(id=article_id)
    if (request.method == 'POST'):
        article.delete()
        return redirect('index')
    else:
        params = {
            'article': article,
        }
        return render(request, 'blog/delete.html', params)

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block main %}
<h1>Login</h1>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {{ form.as_p }}
    <input type="submit" value="Login" class="btn btn-outline-success">
</form>
{% endblock %}

blog/templates/blog/create.html
{% extends "base.html" %}

{% block main %}
        <h1>New Blog</h1>
        <form action="{% url 'blog:create' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Create Blog">
        </form>

        <br>

        <a href="{% url 'blog:index' %}">Back</a>
{% endblock %}

blog/templates/blog/delete.html
<!DOCTYPE html>
<html lang="ja">

  <head>
    <meta charset="utf-8">
    <title>Blog App</title>
  </head>

  <body>
    <p>
      <strong>Title:</strong>
      {{article.title}}
    </p>

    <p>
      <strong>Content:</strong>
      {{article.content}}
    </p>
    <form action="{% url 'delete' article.id %}" method="post">
      {% csrf_token %}
      <input type="submit" value="Delete">
    </form>

    <br>

    <a href="{% url 'index' %}">Back</a>
  </body>

</html>

blog/templates/blog/detail.html
<!DOCTYPE html>
<html lang="ja">

  <head>
    <meta charset="utf-8">
    <title>Blog App</title>
  </head>

  <body>
    <p>
      <strong>Title:</strong>
      {{article.title}}
    </p>

    <p>
      <strong>Content:</strong>
      {{article.content}}
    </p>
    <a href="{% url 'index' %}">Back</a> |
    <a href="{% url 'edit' article.id %}">Edit</a>
  </body>

</html>

blog/templates/blog/edit.html
<!DOCTYPE html>
<html lang="ja">

  <head>
    <meta charset="utf-8">
    <title>Blog App</title>
  </head>

  <body>
    <h1>Editing Blog</h1>
    <form action="{% url 'edit' article.id %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Update">
    </form>

    <br>

    <a href="{% url 'detail' article.id %}">Detail</a> |
    <a href="{% url 'index' %}">Back</a>
  </body>

</html>

blog/templates/blog/index.html
{% extends "base.html" %}

    {% block main %}
    <h1>Blogs</h1>
    <table>
        <tr>
            <th>Title</th>
            <th>Content</th>
            <th colspan="3"></th>
        </tr>
        {% for article in articles %}
        <tr>
            <td>{{article.title}}</td>
            <td>{{article.content}}</td>
            <td><a href="{% url 'blog:detail' article.id %}">Detail</a></td>
            <td><a href="{% url 'blog:edit' article.id %}">Edit</a></td>
            <td><a href="{% url 'blog:delete' article.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>

    <br>

    <a href="{% url 'blog:create' %}">New Blog</a>

{% endblock %}

templates/base.html
<html>

<head>
    <meta charset="utf-8">
    <title>Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'blog:index' %}">Blog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-md-2">
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'blog:create' %}">New Article</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                     <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Log in</a></li>
                {% endif %}
            </ul>
        <div>
    </nav>
    <main>
        <div class="container">
            {% block main %}
            {% endblock %}
        </div>
    </main>
</body>

</html>